### ISSUE TITLE
TypeError: str vs byte in Python 3

### ISSUE THREAD

**Issue by pdb5627** [saimn/sigal#137]
I get the following error when building a gallery using v0.9.1 or current master from Github under Python 3.  Running with '-v' option avoids the error.  v0.8.1 did not have this issue.

```
$ sigal build
Sorting media  [####################################]  100%
Collecting files  [------------------------------------]    0%
Traceback (most recent call last):
  File "/home/pdb/python-venv/sigal-env/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/sigal/__init__.py", line 133, in build
    gal.build(force=force)
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/sigal/gallery.py", line 565, in build
    media_list = [f for album in albums
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/sigal/gallery.py", line 565, in <listcomp>
    media_list = [f for album in albums
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/_termui_impl.py", line 243, in next
    self.render_progress()
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/_termui_impl.py", line 204, in render_progress
    line = self.format_progress_line()
  File "/home/pdb/python-venv/sigal-env/lib/python3.4/site-packages/click/_termui_impl.py", line 177, in format_progress_line
    }).rstrip()
TypeError: sequence item 1: expected str instance, bytes found
```

**Comment by saimn** [comment]
Thanks for the report, I missed this case on python 3.
