### ISSUE TITLE
struct.error: unpack requires a string argument of length 2

### ISSUE THREAD

**Issue by seansay** [saimn/sigal#157]
just got a new laptop, and install sigal rebuild my album, got this error, any idea?  It's the problem of pillow install?
```
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3368026112 bytes but only got 0. Skipping tag 7
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 134479872 bytes but only got 0. Skipping tag 7
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 4294901760 bytes but only got 0. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1572864 bytes but only got 0. Skipping tag 3
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3300917248 bytes but only got 0. Skipping tag 7
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 0. Skipping tag 3
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 119144448 bytes but only got 0. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 80478208 bytes but only got 0. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 36175872 bytes but only got 0. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 196608 bytes but only got 0. Skipping tag 7
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 8432. Skipping tag 7
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 131073 bytes but only got 8428. Skipping tag 0
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 393216 bytes but only got 0. Skipping tag 3
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 44040192 bytes but only got 0. Skipping tag 5
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 44564480 bytes but only got 0. Skipping tag 5
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 131072 bytes but only got 0. Skipping tag 3
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 45088768 bytes but only got 0. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py:466: UserWarning: Possibly corrupt EXIF data.  Expecting to read 507510784 bytes but only got 8432. Skipping tag 4
  "Skipping tag %s" % (size, len(data), tag))
Traceback (most recent call last):
  File "/Users/sean/.pyenv/versions/sigal/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/__init__.py", line 133, in build
    gal.build(force=force)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 616, in build
    writer.write(album)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/writer.py", line 110, in write
    page = self.template.render(**self.generate_context(album))
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sean/baidu/百度云同步盘/sites/photos.notimportant.org/theme/templates/index.html", line 87, in top-level template code
    data-description="{{ img_description(media) }}"/>
  File "/Users/sean/baidu/百度云同步盘/sites/photos.notimportant.org/theme/templates/index.html", line 70, in template
    {%- if media.exif %}
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/utils.py", line 118, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 157, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/utils.py", line 118, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 163, in raw_exif
    if self.ext in ('.jpg', '.jpeg') else None)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/sigal/image.py", line 166, in get_exif_data
    exif = img._getexif() or {}
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 390, in _getexif
    return _getexif(self)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 419, in _getexif
    info.load(file)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 430, in load
    tag, typ = i16(ifd), i16(ifd, 2)
  File "/Users/sean/.pyenv/versions/sigal/lib/python2.7/site-packages/PIL/_binary.py", line 39, in i16le
    return unpack("<H", c[o:o+2])[0]
struct.error: unpack requires a string argument of length 2
make: *** [build] Error 1
```

**Comment by saimn** [comment]
The issue seems to come from Pillow when it reads the exif tags from one of your image. Maybe you installed a more recent version of Pillow on your new laptop, and a change in Pillow can explain why this happens now ?

**Comment by seansay** [comment]
@saimn 
yes, the last time I build album is a very long time ago...Maybe half year
any way I can see the problem image?

**Comment by saimn** [comment]
@seansay you can run sigal in debug mode to see which image is being processed when the error happens (`sigal build -d -n 1`).

**Comment by seansay** [comment]
@saimn 
also, I remove `_build` dir and build again, has no error now!

**Comment by saimn** [comment]
Ok great, closing then :)

**Comment by seansay** [comment]
@saimn 
Hi, Simon. do you know any easy way to fix exif data?

**Comment by saimn** [comment]
@seansay not really, I have used cli tools like jhead, exiftool or exiv2 to modify exif data for a batch of images, but I don't know if these tools include a way to check and fix the data.
