### ISSUE TITLE
photoswipe: jinja2.exceptions.UndefinedError: 'sigal.gallery.Image object' has no attribute 'size'

### ISSUE THREAD

**Issue by bjoernb** [saimn/sigal#167]
I copied the photoswipe theme from git to the themes directory in the virtualenv and using version 0.9.2 of sigal installed via pip in a virtualenv. This is the traceback I get when running sigal with the path of photoswipe set in sigal.conf.py:

    (sigal)bjoernb@bjoernb ~/public_html/html/images/sigal % sigal build ~/images/foobar ~/public_html/html/images/foobar --title "foobar gallery"
    Sorting media  [####################################]  100%
    Collecting files  [####################################]  100%   
    Processing files  [------------------------------------]  0/0
    
    Traceback (most recent call last):
      File "/home/bjoernb/public_html/html/images/sigal/bin/sigal", line 11, in <module>
        sys.exit(main())
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
        return self.main(*args, **kwargs)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/click/core.py", line 680, in main
        rv = self.invoke(ctx)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
        return callback(*args, **kwargs)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/sigal/__init__.py", line 133, in build
        gal.build(force=force)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/sigal/gallery.py", line 616, in build
        writer.write(album)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/sigal/writer.py", line 110, in write
        page = self.template.render(**self.generate_context(album))
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/sigal/themes/photoswipe/templates/index.html", line 42, in top-level template code
        {% block content %}
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/sigal/themes/photoswipe/templates/index.html", line 80, in block "content"
        <a href="{{ media.filename }}" itemprop="contentUrl" data-size="{{media.size.width}}x{{media.size.height}}">
      File "/home/bjoernb/public_html/html/images/sigal/local/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
        return getattr(obj, attribute)
    jinja2.exceptions.UndefinedError: 'sigal.gallery.Image object' has no attribute 'size'

**Comment by saimn** [comment]
Hi,
You also need the latest version of the code to get the theme work. I should release a new version of sigal soon.
