### ISSUE TITLE
'IndexError: tuple index out of range' when running in Docker container

### ISSUE THREAD

**Issue by hubertbanas** [saimn/sigal#173]
I'm trying to get sigal working in Docker container. Here is the error message I'm getting when generating: 

``` bash
root@a76633b06433:/config# sigal build --verbose --debug
INFO: Reading settings ...
DEBUG: Settings file: sigal.conf.py
DEBUG: Settings:
{'albums_sort_reverse': True,
 'autorotate_images': True,
 'colorbox_column_size': 4,
 'copy_exif_data': False,
 'destination': u'/www/photos',
 'files_to_copy': (),
 'google_analytics': '',
 'ignore_directories': [],
 'ignore_files': [],
 'img_processor': 'ResizeToFit',
 'img_size': (1280, 960),
 'index_in_url': False,
 'jpg_options': {'optimize': True, 'progressive': True, 'quality': 85},
 'keep_orig': False,
 'links': '',
 'locale': '',
 'make_thumbs': True,
 'medias_sort_attr': 'filename',
 'medias_sort_reverse': False,
 'mp4_options': ['-crf', '23', '-strict', '-2'],
 'orig_dir': 'original',
 'orig_link': False,
 'output_filename': 'index.html',
 'piwik': {'site_id': 0, 'tracker_url': ''},
 'plugin_paths': [],
 'plugins': [],
 'show_map': False,
 'source': u'/pictures/',
 'theme': 'galleria',
 'thumb_dir': 'thumbnails',
 'thumb_fit': True,
 'thumb_prefix': '',
 'thumb_size': (280, 210),
 'thumb_suffix': '',
 'thumb_video_delay': '0',
 'title': u'Photo Gallery',
 'use_assets_cdn': True,
 'use_orig': False,
 'video_format': 'webm',
 'video_size': (480, 360),
 'watermark': u'',
 'webm_options': ['-crf', '10', '-b:v', '1.6M', '-qmin', '4', '-qmax', '63'],
 'write_html': True,
 'zip_gallery': False,
 'zip_media_format': 'resized'}
INFO:       Source : /pictures/
INFO:  Destination : /www/photos
INFO:        Theme : galleria
DEBUG: Plugin paths: []
INFO: Using 2 cores
DEBUG: Albums:
[<Album>(path='.', title=u''), <Album>(path=u'2015_08_22-album_002', title=u'2015_08_22-album_002'), <Album>(path=u'2015_09_16-album_004', title=u'2015_09_16-album_004'), <Album>(path=u'2015_09_02-album_003', title=u'2015_09_02-album_003'), <Album>(path=u'2015_07_11-album_001', title=u'2015_07_11-album_001')]
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-01.jpg
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-02.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-02.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-01.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-02.jpg (JPEG)
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-03.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-01.jpg (JPEG)
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-04.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-04.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-03.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-04.jpg (JPEG)
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-05.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-03.jpg (JPEG)
INFO: Processing /pictures/2015_08_22-album_002/2015_08_22-photo-06.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-05.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-05.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-01.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_08_22-album_002/2015_08_22-photo-06.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_08_22-album_002/thumbnails/2015_08_22-photo-06.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-02.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-01.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-01.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-03.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-02.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-02.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-04.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-03.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-03.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-05.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-04.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-04.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-06.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-05.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-06.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-05.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-07.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-06.jpg (JPEG)
INFO: Processing /pictures/2015_09_16-album_004/2015_09_16-photo-08.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-07.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-07.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-01.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_16-album_004/2015_09_16-photo-08.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_16-album_004/thumbnails/2015_09_16-photo-08.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-02.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-01.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-02.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-01.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-03.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-02.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-04.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-03.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-03.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-05.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-04.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-04.jpg (JPEG)
INFO: Processing /pictures/2015_09_02-album_003/2015_09_02-photo-06.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-05.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-05.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-01.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_09_02-album_003/2015_09_02-photo-06.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_09_02-album_003/thumbnails/2015_09_02-photo-06.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-02.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-01.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-02.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-01.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-03.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-02.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-04.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-04.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-03.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-04.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-05.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-03.jpg (JPEG)
INFO: Processing /pictures/2015_07_11-album_001/2015_07_11-photo-06.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-05.jpg (JPEG)
DEBUG: Save resized image to /www/photos/2015_07_11-album_001/2015_07_11-photo-06.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-06.jpg (JPEG)
DEBUG: Save thumnail image: /www/photos/2015_07_11-album_001/thumbnails/2015_07_11-photo-05.jpg (JPEG)

INFO: Theme  : /usr/local/lib/python2.7/dist-packages/sigal/themes/galleria
INFO: Output album : <Album>(path='.', title=u'')
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2015_09_16-album_004', title=u'2015_09_16-album_004') : 2015_09_16-album_004/thumbnails/2015_09_16-photo-01.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2015_09_02-album_003', title=u'2015_09_02-album_003') : 2015_09_02-album_003/thumbnails/2015_09_02-photo-01.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2015_08_22-album_002', title=u'2015_08_22-album_002') : 2015_08_22-album_002/thumbnails/2015_08_22-photo-01.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2015_07_11-album_001', title=u'2015_07_11-album_001') : 2015_07_11-album_001/thumbnails/2015_07_11-photo-01.jpg
INFO: Output album : <Album>(path=u'2015_08_22-album_002', title=u'2015_08_22-album_002')
DEBUG: Skipped invalid FNumber: (4.2,)
DEBUG: Skipped invalid FocalLength: (8.5,)
Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/usr/local/lib/python2.7/dist-packages/sigal/gallery.py", line 645, in build
    writer.write(album)
  File "/usr/local/lib/python2.7/dist-packages/sigal/writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/sigal/themes/galleria/templates/index.html", line 140, in top-level template code
    data-description="{{ img_description(media) }}"
  File "/usr/local/lib/python2.7/dist-packages/sigal/themes/galleria/templates/index.html", line 109, in template
    {%- if media.exif %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/dist-packages/sigal/utils.py", line 134, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/sigal/gallery.py", line 159, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "/usr/local/lib/python2.7/dist-packages/sigal/image.py", line 228, in get_exif_tags
    simple['exposure'] = '{0}/{1}'.format(*data['ExposureTime'])
IndexError: tuple index out of range
```

``` bash
root@a76633b06433:/config# sigal --version
sigal, version 1.0.0
```

``` bash
root@a76633b06433:/config# pip install --upgrade sigal click jinja2 pilkit Pillow markdown
Requirement already up-to-date: sigal in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: click in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pilkit in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: markdown in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

I'm not sure but I believe I have all of the dependencies installed. Any suggestions appreciated. Thanks.

**Comment by saimn** [comment]
Hi,
it seems to be an issue with the latest version of Pillow (3.0), see #172 
Installing the previous version should solve the issue: `pip install -U Pillow==2.9.0`

**Comment by hubertbanas** [comment]
Yeap, that did it. After downgrading Pillow to version 2.9.0 I was able to successfully generate in Docker container. I guess it was just bad timing and had nothing to do with the fact I was trying sigal in Docker for the first time.
Thank you!
