### ISSUE TITLE
'sigal.gallery.Image object' has no attribute 'exif'

### ISSUE THREAD

**Issue by alanorth** [saimn/sigal#180]
I added a few images to a working gallery and now the build fails with some exif errors at the Jinja build step:

```
$ sigal build            
Sorting media  [####################################]  100%
Collecting files  [####################################]  100%                  
Processing files  [####################################]  282/282          

Traceback (most recent call last):
  File "/Users/aorth/.pyenv/versions/sigal34/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/sigal/gallery.py", line 645, in build
    writer.write(album)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/sigal/writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/sigal/themes/photoswipe/templates/index.html", line 40, in top-level template code
    {% block content %}
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/sigal/themes/photoswipe/templates/index.html", line 79, in block "content"
    <img src="{{ theme.url }}/echo/blank.gif" data-echo="{{ media.filename }}" alt="{{ media.filename }}" itemprop="thumbnail" title="{{ media.exif.datetime }}" />
  File "/Users/aorth/.pyenv/versions/sigal34/lib/python3.4/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'sigal.gallery.Image object' has no attribute 'exif'
```

If I remove the new directory of pictures the build is successful again. Happens on Mac OS X as well as Linux, with Sigal 1.0.0 on Python 3.4.3 and 3.5.0 (via pyenv).

**Comment by saimn** [comment]
There is an issue with the latest version of Pillow and exif metadata : #172
You can install the previous version of Pillow (`pip install Pillow==2.9.0`), and let's hope it will be fixed soon.

**Comment by alanorth** [comment]
Indeed! I installed 2.9.0 and it's working again. *sigh*! Thanks.
