### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by yuvadm** [saimn/sigal#183]
I'm getting this error with many different configurations, have no workaround for it:

```
INFO:       Source : <src>
INFO:  Destination : <dest>
INFO:        Theme : galleria
DEBUG: Plugin paths: []
INFO: Using 1 cores
DEBUG: Albums:
[<Album>(path='.', title=u'img')]
INFO: Processing IMG_9999.JPG
DEBUG: Save thumnail image: IMG_9999.JPG (JPEG)

INFO: Theme  : /home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/themes/galleria
INFO: Output album : <Album>(path='.', title=u'img')
Traceback (most recent call last):
  File "/home/yuval/.virtualenvs/sigal/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 645, in build
    writer.write(album)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/themes/galleria/templates/index.html", line 140, in top-level template code
    data-description="{{ img_description(media) }}"
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/themes/galleria/templates/index.html", line 109, in template
    {%- if media.exif %}
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/utils.py", line 134, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 159, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/utils.py", line 134, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/gallery.py", line 165, in raw_exif
    if self.ext in ('.jpg', '.jpeg') else None)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/sigal/image.py", line 183, in get_exif_data
    exif = img._getexif() or {}
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 391, in _getexif
    return _getexif(self)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 425, in _getexif
    exif.update(info)
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 354, in __getitem__
    self[tag] = handler(self, data, self.legacy_api)  # check type
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 484, in load_rational
    for num, denom in zip(vals[::2], vals[1::2]))
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 484, in <genexpr>
    for num, denom in zip(vals[::2], vals[1::2]))
  File "/home/yuval/.virtualenvs/sigal/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 482, in <lambda>
    combine = lambda a, b: (a, b) if legacy_api else a / b
ZeroDivisionError: division by zero
```

**Comment by yuvadm** [comment]
Source: https://github.com/python-pillow/Pillow/pull/1492

**Comment by saimn** [comment]
Yes, also see #172.
I made some commits to workaround this new behavior in Pillow 3.0, and I was waiting for a possible bugfix release for the GPS exif data, but maybe I should release a new version of sigal just for the ZeroDivisionError.

**Comment by saimn** [comment]
Pillow 3.1.0 is out and this is fixed.
