### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by narnaud** [saimn/sigal#193]
I'm running Sigal with Python 3.5.1, Pillow 3.1.1, and when trying to build here is the result:

Traceback (most recent call last):
  File "c:\python\3.5.1\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\3.5.1\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[...]\build\Scripts\sigal.exe\__main__.py", line 9, in <module>
  File "[...]\build\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "[...]\build\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "[...]\build\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]\build\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]\build\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "[...]\build\lib\site-packages\sigal\__init__.py", line 142, in build
    gal.build(force=force)
  File "[...]\build\lib\site-packages\sigal\gallery.py", line 645, in build
    writer.write(album)
  File "[...]\build\lib\site-packages\sigal\writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "[...]\build\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "[...]\build\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "[...]\build\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "[...]\theme-sigal\templates\index.html", line 94, in top-level template code
    <a href="{{ media.filename }}" class="gallery" title="{{ media.filename }}" {{ img_description(media) }}>
  File "[...]\theme-sigal\templates\index.html", line 82, in template
    {% if media.exif %}
  File "[...]\build\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "[...]\build\lib\site-packages\sigal\utils.py", line 134, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "[...]\build\lib\site-packages\sigal\gallery.py", line 159, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "[...]\build\lib\site-packages\sigal\image.py", line 259, in get_exif_tags
    simple['exposure'] = exptime[0] / float(exptime[1])
ZeroDivisionError: float division by zero

**Comment by saimn** [comment]
Could you run `sigal build -fd -n 1` to identify the problematic image ? Then if you can send me this image so I can test with it ?
