### ISSUE TITLE
feed plugin and german characters

### ISSUE THREAD

**Issue by ThomasRgbg** [saimn/sigal#194]
Hi, 

I just tried the new feed plugin, but I guess, it fails due to a German special character (Ä, Ö, Ü...)

```
Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 9, in <module>
    load_entry_point('sigal==1.1.0-dev', 'console_scripts', 'sigal')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sigal-1.1.0_dev-py2.7.egg/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/usr/local/lib/python2.7/dist-packages/sigal-1.1.0_dev-py2.7.egg/sigal/gallery.py", line 661, in build
    signals.gallery_build.send(self)
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python2.7/dist-packages/sigal-1.1.0_dev-py2.7.egg/sigal/plugins/feeds.py", line 41, in generate_feeds
    generate_feed(gallery, images, feed_type='rss', **settings['rss_feed'])
  File "/usr/local/lib/python2.7/dist-packages/sigal-1.1.0_dev-py2.7.egg/sigal/plugins/feeds.py", line 76, in generate_feed
    feed.write(f, 'utf-8')
  File "/usr/local/lib/python2.7/dist-packages/feedgenerator/django/utils/feedgenerator.py", line 217, in write
    self.add_root_elements(handler)
  File "/usr/local/lib/python2.7/dist-packages/feedgenerator/django/utils/feedgenerator.py", line 235, in add_root_elements
    handler.addQuickElement("description", self.feed['description'])
  File "/usr/local/lib/python2.7/dist-packages/feedgenerator/django/utils/xmlutils.py", line 15, in addQuickElement
    self.characters(contents)
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 185, in characters
    self._write(escape(content))
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 104, in write
    self.flush()
  File "/usr/lib/python2.7/codecs.py", line 688, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 103: ordinal not in range(128)
```
In the config file I have set locale = 'de_DE.UTF-8'

**Comment by saimn** [comment]
Fixed, thanks for the report @ThomasRgbg
