### ISSUE TITLE
Install fails with Pip on Debian

### ISSUE THREAD

**Issue by hjek** [saimn/sigal#206]
**Pip** install fails on **Debian**. Same error with `pip2` and `pip3`:

```
pelle@debian:~$ pip install sigal
Collecting sigal
  Using cached sigal-1.1.0-py2.py3-none-any.whl
Collecting Jinja2 (from sigal)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting Markdown (from sigal)
  Using cached Markdown-2.6.6.zip
Collecting pilkit (from sigal)
  Using cached pilkit-1.1.13.tar.gz
Collecting blinker (from sigal)
  Using cached blinker-1.4.tar.gz
Collecting Pillow (from sigal)
  Using cached Pillow-3.2.0.zip
Collecting click (from sigal)
Collecting MarkupSafe (from Jinja2->sigal)
  Using cached MarkupSafe-0.23.tar.gz
Building wheels for collected packages: Markdown, pilkit, blinker, Pillow, MarkupSafe
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /home/pelle/.cache/pip/wheels/b4/34/8a/0f8b716aab588dbe90091032f0fd8f98ca2e5e75b222b63659
  Running setup.py bdist_wheel for pilkit ... done
  Stored in directory: /home/pelle/.cache/pip/wheels/e3/bb/39/a77bfc6fea2e2d9b21408d37275b6c8bcdd5381dd21d9cf733
  Running setup.py bdist_wheel for blinker ... done
  Stored in directory: /home/pelle/.cache/pip/wheels/7b/8a/eb/5a4f4444f366c515073db8a129c92d4727ad945e5e64b9e8bd
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4quU2O/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmprVfraspip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-2.7/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-4quU2O/Pillow/setup.py", line 767, in <module>
      zip_safe=not debug_build(), )
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-4quU2O/Pillow/setup.py", line 512, in build_extensions
      ' using --disable-%s, aborting' % (f, f))
  ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /home/pelle/.cache/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
Successfully built Markdown pilkit blinker MarkupSafe
Failed to build Pillow
Installing collected packages: MarkupSafe, Jinja2, Markdown, pilkit, blinker, Pillow, click, sigal
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4quU2O/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NaRQmM-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-2.7/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4quU2O/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(), )
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-4quU2O/Pillow/setup.py", line 512, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4quU2O/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NaRQmM-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-4quU2O/Pillow/
```

**Comment by hjek** [comment]
Here on **Debian Testing**, I had to get some additional packages:
`sudo apt install zlib1g-dev python-imaging  libjpeg-dev`

You should [installation instructions](http://sigal.saimon.org/en/latest/installation.html) to include these packages. Additionally the package `build-dep` (mentioned in the instructions) exists neither on **Ubuntu Wily** nor **Debian Testing**.

**Comment by saimn** [comment]
`build-dep` is a sub-command of `apt-get` so it should be available by default on Debian/Ubuntu ? So this command from the docs should install the dependencies to build Pillow. 
But it's true that these installation instructions are a bit outdated, I think now Debian stable and Ubuntu install Pillow instead of PIL.

**Comment by hjek** [comment]
Oh, sorry, misread `build-dep` as a package name. Would still be good to add all dependencies to the docs though, just for people who are bad at guessing or reading long error messages.

**Comment by anarcat** [comment]
isn't this a bug in pillow more than sigal itself?

**Comment by saimn** [comment]
Not really a bug, it's an installation issue (for Pillow). Actually the issue is still open as I wanted to improve the installation docs.

**Comment by saimn** [comment]
I added a note in bdf74d6.
