### ISSUE TITLE
'ascii' codec can't decode byte …

### ISSUE THREAD

**Issue by BrokenVentilator** [saimn/sigal#217]
Hello.

I've tried to run `sigal build`, but I get an `UnicodeDecodeError: ordinal not in range(128)`.

Sigal don't like accent in author name.

**Comment by saimn** [comment]
I cannot reproduce, could you give more details, and the traceback, thanks.

**Comment by saimn** [comment]
Please reopen and give more details if you still have this issue.

**Comment by KwadroNaut** [comment]
Having the same problem with the most basice setup (pip install; sigal init; sigal build)

```
 sigal build -fd -n1
INFO: Reading settings ...
DEBUG: Settings file: sigal.conf.py
DEBUG: Rewrite source : pictures -> /sigal/pictures
DEBUG: Rewrite destination : _build -> /sigal/_build
DEBUG: Settings:
{'albums_sort_attr': 'name',
 'albums_sort_reverse': False,
 'autorotate_images': True,
 'colorbox_column_size': 4,
 'copy_exif_data': False,
 'destination': u'/sigal/_build',
 'files_to_copy': (),
 'google_analytics': '',
 'google_tag_manager': '',
 'ignore_directories': [],
 'ignore_files': [],
 'img_processor': 'ResizeToFit',
 'img_size': (800, 600),
 'index_in_url': False,
 'jpg_options': {'optimize': True, 'progressive': True, 'quality': 85},
 'keep_orig': False,
 'leaflet_provider': 'OpenStreetMap.Mapnik',
 'links': '',
 'locale': '',
 'make_thumbs': True,
 'medias_sort_attr': 'filename',
 'medias_sort_reverse': False,
 'mp4_options': ['-crf', '23', '-strict', '-2'],
 'orig_dir': 'original',
 'orig_link': False,
 'output_filename': 'index.html',
 'piwik': {'site_id': 0, 'tracker_url': ''},
 'plugin_paths': [],
 'plugins': [],
 'show_map': False,
 'source': u'/sigal/pictures',
 'theme': 'galleria',
 'thumb_dir': 'thumbnails',
 'thumb_fit': True,
 'thumb_prefix': '',
 'thumb_size': (280, 210),
 'thumb_suffix': '',
 'thumb_video_delay': '0',
 'title': '',
 'use_assets_cdn': True,
 'use_orig': False,
 'video_format': 'webm',
 'video_size': (480, 360),
 'watermark': u'',
 'webm_options': ['-crf', '10', '-b:v', '1.6M', '-qmin', '4', '-qmax', '63'],
 'write_html': True,
 'zip_gallery': False,
 'zip_media_format': 'resized'}
INFO:       Source : /sigal/pictures
INFO:  Destination : /sigal/_build
INFO:        Theme : galleria
DEBUG: Plugin paths: []
INFO: Using 1 cores
Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sigal/__init__.py", line 141, in build
    gal = Gallery(settings, ncpu=ncpu)
  File "/usr/local/lib/python2.7/dist-packages/sigal/gallery.py", line 518, in __init__
    topdown=False):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```

**Comment by KwadroNaut** [comment]
Setting ENV LANG C.UTF-8 solves this.
