### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#251]
Ran sigal and got the following error, upgrade to 1.3.0 and the error remains. I have no idea what this means, but happy to provide files if that will help.

```

Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 668, in build
    writer.write(album)
  File "/usr/local/lib/python2.7/site-packages/sigal/writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 63, in block "content"
    {{ img_description(media) }}>
  File "/usr/local/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 42, in template
    {% if media.exif %}
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/site-packages/sigal/utils.py", line 139, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 157, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "/usr/local/lib/python2.7/site-packages/sigal/image.py", line 304, in get_exif_tags
    lat = dms_to_degrees(lat_info)
  File "/usr/local/lib/python2.7/site-packages/sigal/image.py", line 217, in dms_to_degrees
    d = float(v[0][0]) / float(v[0][1])
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by saimn** [comment]
There was a few issues with Pillow, which version do you have ? Maybe test with the latest one if you don't have it yet.

**Comment by reagle** [comment]
I updated everything before I sent my message:

```
pilkit (2.0)
Pillow (4.2.0)
sigal (1.3.0)
```

**Comment by reagle** [comment]
On 7/5/17 9:22 AM, Simon Conseil wrote:
> There was a few issues with Pillow, which version do you have ? Maybe
> test with the latest one if you don't have it yet.

I updated everything before I sent my message:

```
pilkit (2.0)
Pillow (4.2.0)
sigal (1.3.0)
```

**Comment by saimn** [comment]
Could you send me the image by email, or print the GPS metadata here ? (though I'm afraid I will not have much time to look at this in the next weeks)

**Comment by reagle** [comment]
How do I know which image it is choking on? I don't see the file name in the traceback. I don't see a --verbose flag either?

**Comment by saimn** [comment]
Running sigal in debug mode and without parallelism will give you the info on the image being processed: `sigal build -fd -n 1`

**Comment by reagle** [comment]
BTW: Could include those switches in the help message.

**Comment by reagle** [comment]
When I run it with those switches, ffmpeg gets stuck encoding a 47MB video files (should have finished long ago, but keeps using CPU):

```
DEBUG: Video size: 1440, 1080 -> 640, 480
DEBUG: Processing video: ffmpeg -i /Volumes/media/reagle/f/photo/hires/2014/10/15-1550-beach-casper-wingaersheek.mp4 -y -b:v 885k -r 23.976 -preset medium -ab 127k -strict -2 -vf scale=640:trunc(ow/a/2)*2 /Volumes/media/reagle/f/photo/gallery/2014/10/15-1550-beach-casper-wingaersheek.webm
```

**Comment by reagle** [comment]
```
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libvpx --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
```

**Comment by reagle** [comment]
That's the first mp4 it encounters. I wonder if ffmpeg 3.3 introduced big changes...?

**Comment by reagle** [comment]
Falling back to ffmpeg2.8 results in this error:
```
DEBUG: Video size: 1440, 1080 -> 640, 480
DEBUG: Processing video: ffmpeg -i /Volumes/media/reagle/f/photo/hires/2014/10/04-1402-casper-zyggy.mp4 -y -b:v 885k -r 23.976 -preset medium -ab 127k -strict -2 -vf scale=640:trunc(ow/a/2)*2 /Volumes/media/reagle/f/photo/gallery/2014/10/04-1402-casper-zyggy.webm
DEBUG: STDOUT:

DEBUG: STDERR:
 ffmpeg version 2.8.11 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix='/usr/local/Cellar/ffmpeg@2.8/2.8.11' --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Volumes/media/reagle/f/photo/hires/2014/10/04-1402-casper-zyggy.mp4':
  Metadata:
    major_brand     : MSNV
    minor_version   : 19595376
    compatible_brands: MSNVmp42isom
    creation_time   : 2014-10-04 16:18:04
  Duration: 00:00:19.52, start: 0.000000, bitrate: 12163 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1440x1080 [SAR 4:3 DAR 16:9], 12032 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2014-10-04 16:18:04
      handler_name    : Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2014-10-04 16:18:04
      handler_name    : Sound Media Handler
Output #0, webm, to '/Volumes/media/reagle/f/photo/gallery/2014/10/04-1402-casper-zyggy.webm':
  Metadata:
    major_brand     : MSNV
    minor_version   : 19595376
    compatible_brands: MSNVmp42isom
    Stream #0:0(und): Video: vp8, none, q=2-31, 128 kb/s (default)
    Metadata:
      creation_time   : 2014-10-04 16:18:04
      handler_name    : Video Media Handler
    Stream #0:1(und): Audio: vorbis, 0 channels, 128 kb/s
    Metadata:
      creation_time   : 2014-10-04 16:18:04
      handler_name    : Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> ? (?))
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (native))
Encoder (codec vp8) not found for output stream #0:0

DEBUG: Removing file /Volumes/media/reagle/f/photo/gallery/2014/10/04-1402-casper-zyggy.webm
Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 657, in build
    res = process_file(media_item)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 700, in process_file
    ret = processor(*args[3:])
  File "/usr/local/lib/python2.7/site-packages/sigal/video.py", line 170, in process_video
    options=settings.get(video_format + '_options'))
  File "/usr/local/lib/python2.7/site-packages/sigal/video.py", line 127, in generate_video
    check_subprocess(cmd, source, outname)
  File "/usr/local/lib/python2.7/site-packages/sigal/video.py", line 61, in check_subprocess
    raise SubprocessException('Failed to process ' + source)
sigal.video.SubprocessException: Failed to process /Volumes/media/reagle/f/photo/hires/2014/10/04-1402-casper-zyggy.mp4
```

**Comment by reagle** [comment]
ffmpeg/vp8 is probably a separate issue. I switched to mp4 and ran a build without `-fd -n 1' and video seemed to go fine but it choked as I mentioned at the top, so rerunning with those switches turned on.

**Comment by saimn** [comment]
> ffmpeg/vp8 is probably a separate issue.

yeah, in debug mode Sigal crashes if the ffmpeg process had an error, to help debugging. In normal it just issue a warning and continue the processing.

**Comment by reagle** [comment]
I'm not sure which file is causing the problem, but here's a debug run.

```
INFO: Processing /Volumes/media/reagle/f/photo/hires/2017/05/20-1417-nora-casper.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /Volumes/media/reagle/f/photo/gallery/2017/05/20-1417-nora-casper.jpg (JPEG)
DEBUG: Save thumnail image: /Volumes/media/reagle/f/photo/gallery/2017/05/thumbs/20-1417-nora-casper.jpg (JPEG)
INFO: Processing /Volumes/media/reagle/f/photo/hires/2017/05/20-1423-casper.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /Volumes/media/reagle/f/photo/gallery/2017/05/20-1423-casper.jpg (JPEG)
DEBUG: Save thumnail image: /Volumes/media/reagle/f/photo/gallery/2017/05/thumbs/20-1423-casper.jpg (JPEG)

INFO: Theme  : /usr/local/lib/python2.7/site-packages/sigal/themes/colorbox
INFO: Output album : <Album>(path='.', title=u'Stolen Souls')
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/07', title=u'07') : 07/thumbs/01-1242-cecilia-greg-lisa.jpg
DEBUG: Using thumbnail from sub-directory for <Album>(path=u'2017', title=u'2017') : 2017/07/thumbs/01-1242-cecilia-greg-lisa.jpg
INFO: Output album : <Album>(path=u'2017/02', title=u'02')
INFO: Output album : <Album>(path=u'2017', title=u'2017')
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/06', title=u'06') : 06/thumbs/03-1704-books.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/05', title=u'05') : 05/thumbs/07-1107-sky.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/04', title=u'04') : 04/thumbs/02-1119-sky.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/02', title=u'02') : 02/thumbs/10-1922-casper.jpg
DEBUG: Use 1st landscape image as thumbnail for <Album>(path=u'2017/01', title=u'01') : 01/thumbs/01-1231-casper-dogs.jpg
INFO: Output album : <Album>(path=u'2017/01', title=u'01')
INFO: Output album : <Album>(path=u'2017/06', title=u'06')
INFO: Output album : <Album>(path=u'2017/07', title=u'07')
Traceback (most recent call last):
  File "/usr/local/bin/sigal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sigal/__init__.py", line 142, in build
    gal.build(force=force)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 668, in build
    writer.write(album)
  File "/usr/local/lib/python2.7/site-packages/sigal/writer.py", line 111, in write
    page = self.template.render(**self.generate_context(album))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/base.html", line 45, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 63, in block "content"
    {{ img_description(media) }}>
  File "/usr/local/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python2.7/site-packages/sigal/themes/colorbox/templates/index.html", line 42, in template
    {% if media.exif %}
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/site-packages/sigal/utils.py", line 139, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/sigal/gallery.py", line 157, in exif
    if self.raw_exif and self.ext in ('.jpg', '.jpeg') else None)
  File "/usr/local/lib/python2.7/site-packages/sigal/image.py", line 304, in get_exif_tags
    lat = dms_to_degrees(lat_info)
  File "/usr/local/lib/python2.7/site-packages/sigal/image.py", line 217, in dms_to_degrees
    d = float(v[0][0]) / float(v[0][1])
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by reagle** [comment]
Okay, I've isolated the JPEGs. This weekend I experimented with a new workflow (developing raws on my Android tablet using snapseed) so I suspect this is the thing that changed.

**Comment by reagle** [comment]
Thanks!
