### ISSUE TITLE
Traceback on IPTC parsing

### ISSUE THREAD

**Issue by bazuchan** [saimn/sigal#330]
```$ sigal build
Collecting albums /Traceback (most recent call last):
  File "/usr/bin/sigal", line 11, in <module>
    load_entry_point('sigal==1.4.0', 'console_scripts', 'sigal')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sigal/__init__.py", line 141, in build
    gal = Gallery(settings, ncpu=ncpu)
  File "/usr/lib/python3/dist-packages/sigal/gallery.py", line 582, in __init__
    album = Album(relpath, settings, dirs, files, self)
  File "/usr/lib/python3/dist-packages/sigal/gallery.py", line 277, in __init__
    media = Image(f, self.path, settings)
  File "/usr/lib/python3/dist-packages/sigal/gallery.py", line 86, in __init__
    self._get_metadata()
  File "/usr/lib/python3/dist-packages/sigal/gallery.py", line 178, in _get_metadata
    iptc_data = get_iptc_data(self.src_path)
  File "/usr/lib/python3/dist-packages/sigal/image.py", line 254, in get_iptc_data
    iptc_data["description"] = raw_iptc[(2, 120)].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte```

Image file is https://transfer.sh/1cQkK/SANY2984.JPG

**Comment by saimn** [comment]
Thanks for the report, this was fixed in #316, but not released yet (I should probably think about making this release!).
