### ISSUE TITLE
Huge images cause PIL.Image.DecompressionBombError exception

### ISSUE THREAD

**Issue by Roliga** [saimn/sigal#332]
Apparently for very large images PIL raises an exception instead of just the warning Sigal currently handles: [PIL docs](https://pillow.readthedocs.io/en/5.2.x/releasenotes/5.0.0.html?highlight=decompressionbomberror#decompression-bombs-now-raise-exceptions)

Example trace:
```
Traceback (most recent call last):
  File "/usr/bin/sigal", line 11, in <module>
    load_entry_point('sigal==2.0.dev0', 'console_scripts', 'sigal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sigal/__init__.py", line 143, in build
    gal.build(force=force)
  File "/usr/lib/python3.6/site-packages/sigal/gallery.py", line 713, in build
    writer.write(album)
  File "/usr/lib/python3.6/site-packages/sigal/writer.py", line 118, in write
    page = self.template.render(**self.generate_context(album))
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/sigal/themes/photoswipe/templates/index.html", line 40, in top-level template code
    {% block content %}
  File "/usr/lib/python3.6/site-packages/sigal/themes/photoswipe/templates/index.html", line 85, in block "content"
    <a href="{{ media.filename }}" itemprop="contentUrl" data-size="{{media.size.width}}x{{media.size.height}}">
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/lib/python3.6/site-packages/sigal/utils.py", line 134, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.6/site-packages/sigal/gallery.py", line 201, in size
    return get_size(self.dst_path)
  File "/usr/lib/python3.6/site-packages/sigal/image.py", line 199, in get_size
    im = _read_image(file_path)
  File "/usr/lib/python3.6/site-packages/sigal/image.py", line 61, in _read_image
    im = PILImage.open(file_path)
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 2609, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 2600, in _open_core
    _decompression_bomb_check(im.size)
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 2539, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError
```

**Comment by saimn** [comment]
I guess we could add a setting to disable this. How big is your image ?

**Comment by Roliga** [comment]
The image I had was ~30000x30000 pixels. I suppose ideally such big images would just be skipped, since PIL would use way too much memory to process them.

**Comment by saimn** [comment]
Yes, if you don't want this image to be processed the solution is to use the existing `ignore_*` options. I don't like the silent skip solution, but the error should be caught and reported. But here the failure happen while rendering the template, so this is a bit more annoying. Did you disable the resizing, or do you also see an error before ?

**Comment by MarinBernard** [comment]
I've met the same issue, but I would like the images to be processed. Is there a way to tell PIL to use a higher limit? If not, would it be possible to implement a new setting to do that ?

**Comment by saimn** [comment]
The limit can be set on `PIL.Image.MAX_IMAGE_PIXELS`, we could set this with a new setting in sigal (contribution welcome ;)).

https://github.com/python-pillow/Pillow/blob/08c47925d0ffd6ca64b938f2439b17d01db1f67a/src/PIL/Image.py#L2719-L2735
