### ISSUE TITLE
albums_sort_attr=date conflicts with subdirectories

### ISSUE THREAD

**Issue by Mousketeer** [saimn/sigal#389]
Setting albums_sort_attr=date in sigal.conf.py when subdirectories are used causes the build process to fail with sort_subdirs -> AttributeError: 'Album' object has no attribute 'date'.

Commenting out the config statement (not sure what it defaults to) makes the build succeed, just as moving to a single (flat) directory.
Currently I don't have time to dig into this, just reporting for now.

Sigal version 2.0, python 3.6, Debian-derived linux distro

```
Directory structure:
macro_src/subalbumone
macro_src/subalbumtwo
```

```
./sigal build -f -d -n 1 macro_src/ macro
INFO: Reading settings ...
DEBUG: Settings file: sigal.conf.py
DEBUG: Rewrite source : test_src/ -> /home/m/albums/test_src
DEBUG: Rewrite destination : test/ -> /home/m/albums/test
DEBUG: Settings:
{'albums_sort_attr': 'date',
 'albums_sort_reverse': False,
 'author': 'Moi',
 'autorotate_images': True,
 'colorbox_column_size': 3,
 'compress_assets_options': {'method': 'gzip'},
 'copy_exif_data': False,
 'datetime_format': '%c',
 'destination': '/home/m/albums/test',
 'files_to_copy': (),
 'google_analytics': '',
 'google_tag_manager': '',
 'html_language': 'en',
 'ignore_directories': [],
 'ignore_files': [],
 'img_extensions': ['.jpg', '.jpeg', '.png', '.gif'],
 'img_processor': 'ResizeToFit',
 'img_size': (1024, 768),
 'index_in_url': False,
 'jpg_options': {'optimize': True, 'progressive': True, 'quality': 85},
 'keep_orig': True,
 'leaflet_provider': 'OpenStreetMap.Mapnik',
 'links': '',
 'locale': '',
 'make_thumbs': True,
 'medias_sort_attr': 'filename',
 'medias_sort_reverse': False,
 'mp4_options': ['-crf', '23', '-strict', '-2'],
 'orig_dir': 'original',
 'orig_link': False,
 'output_filename': 'index.html',
 'piwik': {'site_id': 0, 'tracker_url': ''},
 'plugin_paths': [],
 'plugins': ['sigal.plugins.compress_assets'],
 'show_map': True,
 'site_logo': '',
 'source': '/home/m/albums/test_src',
 'theme': 'colorbox',
 'thumb_dir': 'thumbnails',
 'thumb_fit': True,
 'thumb_fit_centering': (0.5, 0.5),
 'thumb_prefix': '',
 'thumb_size': (280, 210),
 'thumb_suffix': '',
 'thumb_video_delay': '0',
 'title': 'Macro',
 'use_orig': False,
 'video_converter': 'ffmpeg',
 'video_extensions': ['.mov', '.avi', '.mp4', '.webm', '.ogv', '.3gp'],
 'video_format': 'webm',
 'video_size': (1280, 720),
 'watermark': '',
 'webm_options': ['-crf', '10', '-b:v', '1.6M', '-qmin', '4', '-qmax', '63'],
 'write_html': True,
 'zip_gallery': 'archive.zip',
 'zip_media_format': 'orig',
 'zip_skip_if_exists': False}
INFO:       Source : /home/m/albums/macro_src
INFO:  Destination : /home/m/albums/macro
INFO:        Theme : colorbox
DEBUG: Plugin paths: []
DEBUG: Registered plugin sigal.plugins.compress_assets
INFO: Using 1 cores
Collecting albums, done.
Traceback (most recent call last):
  File "./sigal", line 11, in <module>
    sys.exit(main())
  File "/home/m/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/m/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/m/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/m/.local/lib/python3.6/site-packages/sigal/__init__.py", line 140, in build
    gal = Gallery(settings, ncpu=ncpu)
  File "/home/m/.local/lib/python3.6/site-packages/sigal/gallery.py", line 620, in __init__
    album.sort_subdirs(settings['albums_sort_attr'])
  File "/home/m/.local/lib/python3.6/site-packages/sigal/gallery.py", line 372, in sort_subdirs
    reverse=self.settings['albums_sort_reverse'])
  File "/home/m/.local/lib/python3.6/site-packages/sigal/gallery.py", line 367, in <lambda>
    albums_sort_attr))
AttributeError: 'Album' object has no attribute 'date'

```

**Comment by saimn** [comment]
Hi,
`date` is not a valid option for `albums_sort_attr`. What would be the date in this case ?

**Comment by Mousketeer** [comment]
Now I can't find the reason I ever used date as a sort key. It could be the date of the last/first image contained therein.
Let's write this off as pbcak, apologies for wasting your time.
